version: "3.4"
services:

  example_proxy:
    container_name: example_proxy
    image: example_proxy
    build:
      context: ./nginx
      dockerfile: dockerfile
      target: production
      args:
        - EXAMPLE_API_PORT=${EXAMPLE_API_PORT}
    ports:
      - "443:443"
      - "80:80"
    environment:
      - EXAMPLE_API_PORT=${EXAMPLE_API_PORT}
    expose:
      - "443"
      - "80"
    restart: ${RESTART_POLICY:-on-failure}
    networks:
      - example_net
    volumes:
      - ./nginx/keys:/keys

  example_server:
    container_name: example_server
    image: example_server
    build:
      context: ./backend
      dockerfile: dockerfile
    environment:
      - PORT=${EXAMPLE_API_PORT}
    ports:
      - "${EXAMPLE_API_PORT}:${EXAMPLE_API_PORT}"
    expose:
      - "${EXAMPLE_API_PORT}"
    depends_on:
      example_db:
        condition: service_healthy
    restart: ${RESTART_POLICY:-on-failure}
    networks:
      - example_net

  example_db:
    container_name: example_db
    image: postgres_db
    restart: ${RESTART_POLICY:-on-failure}
    build:
      context: ./database
      dockerfile: dockerfile
    ports:
      - 127.0.0.1:5432:5432
    expose:
      - "5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - example_net
    volumes:
      - example_data:/var/lib/postgresql

  adminer:
    container_name: adminer
    image: adminer
    restart: ${RESTART_POLICY:-on-failure}
    ports:
      - 127.0.0.1:8080:8080
    networks:
      - example_net

  example_frontend:
    container_name: example_frontend
    image: example_frontend
    build:
      context: ./frontend
      target: ${TARGET}
      dockerfile: dockerfile
    environment:
      - PORT=${EXAMPLE_FRONTEND_PORT}
    ports:
      - "${EXAMPLE_FRONTEND_PORT}:${EXAMPLE_FRONTEND_PORT}"
    expose:
      - "${EXAMPLE_FRONTEND_PORT}"
    restart: ${RESTART_POLICY:-on-failure}
    networks:
      - example_net
    volumes:
      - ./frontend/src:/app/src


networks:
  example_net:
    external: true

volumes:
  example_data:
