FROM golang:1.22-alpine

WORKDIR /app

RUN apk add --no-cache bash
COPY ./docker-utils/wait-for-it.sh /wait-for-it.sh
RUN chmod +x /wait-for-it.sh

COPY go.mod ./
COPY go.sum ./

RUN go mod download

COPY . ./

RUN go build -o /server

CMD ["/wait-for-it.sh", "example_db:5432", "--", "/server"]
