FROM nginx:latest as common

# Just use root for this
USER root

# make sure nginx folders exist
RUN mkdir -p /etc/nginx/sites-available
RUN mkdir -p /etc/nginx/sites-enabled

# routes go here
RUN mkdir -p /etc/nginx/locations

# keys are mounted here
RUN mkdir -p /keys

# prepare the volume
# https://github.com/nodejs/docker-node/blob/cbbf60da587a7ca135b573f4c05810d88f04ace7/16/buster/Dockerfile
# nginx needs to understand this user with id 1000
RUN groupadd --gid 1000 node \
  && useradd --uid 1000 --gid node --shell /bin/bash --create-home node

# Expose HTTPS port
EXPOSE 443

# Expose HTTP port to allow for redirects to HTTPS
EXPOSE 80

# copy location (route) data over
COPY ./locations/ /etc/nginx/locations/

# Copy sites-available to container
COPY ./sites-available/. /etc/nginx/sites-available/

# symlink sites-available to sites-enabled for nginx to read
RUN ln -s /etc/nginx/sites-available/* /etc/nginx/sites-enabled/

# These env vars will be used to configure nginx
ARG EXAMPLE_API_PORT
ENV EXAMPLE_API_PORT $EXAMPLE_API_PORT
RUN echo "EXAMPLE_API_PORT=$EXAMPLE_API_PORT"
RUN find /etc/nginx/locations -type f -exec sed -i "s/\${EXAMPLE_API_PORT}/$EXAMPLE_API_PORT/g" {} \;

# DEVELOPMENT ======================================================================================
FROM common as development
WORKDIR /etc/nginx
COPY ./nginx.conf /etc/nginx

# PRODUCTION =======================================================================================
FROM common as production
WORKDIR /etc/nginx
COPY ./nginx.conf /etc/nginx
