# Use postgres/example user/password credentials
version: '3.1'

services:
  db:
    container_name: db_01
    image: postgres
    restart: always
    build:
      context: .
      dockerfile: dockerfile
    ports:
      - 127.0.0.1:5432:5432

  adminer:
    container_name: adminer
    image: adminer
    restart: always
    ports:
      - 127.0.0.1:8080:8080

volumes:
  postgres:
